### ISSUE TITLE
抱歉再次打扰您，想问下ava数据集的mat文件您是如何获得呢？

### ISSUE THREAD

**Issue by pumpkinnan97** [zwx8981/IAA_project#2]
官方给的数据集里我没有找到ava的mat文件，如果可以的话，能不能麻烦您分享下您的mat文件呢？

**Comment by zwx8981** [comment]
@pumpkinnan97 你可以参考这个repo https://github.com/HuiZeng/Unified_IAA

**Comment by pumpkinnan97** [comment]
> @pumpkinnan97 你可以参考这个repo https://github.com/HuiZeng/Unified_IAA

感谢您给的参考，还想再问一下，AVA数据集官方给的train和test set如何得到呢？官方给的文档中说是在aesthetics_image_lists当中有给，但是我只看到不同图像类别的train和test，比如animal_train和animal_test, 并没有看到总的train和test划分呢？能麻烦您告诉我一下您是如何得到的吗？感谢您的帮助！

**Comment by zwx8981** [comment]
@pumpkinnan97 官方给了test，然后剩下的全部是train

**Comment by pumpkinnan97** [comment]
> @pumpkinnan97 官方给了test，然后剩下的全部是train

那我应该是下载的文件有缺少，我没有test文件，如果方便的话，能不能麻烦您给一下test文件或者您下载ava数据集相关的文档的地址呢？我查了很久都只有我现在这个版本的，抱歉打扰您了，很感谢您的帮助！

**Comment by zwx8981** [comment]
[generic_test.txt](https://github.com/zwx8981/IAA_project/files/3766624/generic_test.txt)

**Comment by zwx8981** [comment]
@pumpkinnan97

**Comment by pumpkinnan97** [comment]
> @pumpkinnan97

谢谢您！祝您科研一切顺利呀

**Comment by huanmofazong** [comment]
> 官方给的数据集里我没有找到ava的mat文件，如果可以的话，能不能麻烦您分享下您的mat文件呢？

您好，这个程序您跑通了，想向您请教一下

**Comment by huanmofazong** [comment]
> 官方给的数据集里我没有找到ava的mat文件，如果可以的话，能不能麻烦您分享下您的mat文件呢？

@pumpkinnan97 您好，这个程序您跑通了吗，想向你请教下

**Comment by pumpkinnan97** [comment]
@huanmofazong 我没有跑这份代码，当时是想看下作者有些细节具体怎么实现的。抱歉可能帮不了你
