### ISSUE TITLE
您好，我想请教一下

### ISSUE THREAD

**Issue by huanmofazong** [zwx8981/IAA_project#3]
您好，我在运行这个程序时，使用CUHKPQ数据集，
 line 284, in train
    X = data['image'].to(self.device)
TypeError: list indices must be integers or slices, not str
出现这个错误，我已经把places365的模型放进去了，CUHKPQ数据集的位置也改正确了，然后我把cuhkq的两个trian和val的txt文件名，改成了代码中对应的 train.txt和val.txt。之后运行出现了这个错误，我的代码能力不是太强，还在学习过程当中。您的这篇论文我仔细阅读，觉得网络的创新性很强，特别想学习下。恳请您在百忙之后回复一下，谢谢，祝您科研顺利，生活幸福！

**Comment by zwx8981** [comment]
@huanmofazong 你好，麻烦调试一下看看dataloader返回的X和y分别是什么数据

**Comment by huanmofazong** [comment]
for data in tqdm(data_loader):
            X = data['image'].to(self.device)
            y = data['label'].to(self.device)
就是这段里面的，data[‘image’]不能读取这个数据，print 这个data的type是list类型。
然后我试着把data改成data，target
for data,target in tqdm(data_loader):
            X = data.to(self.device)
            y = target.to(self.device)
代码是可以训练起来，但好像还是有问题
可以请教下原因吗

**Comment by zwx8981** [comment]
@huanmofazong  你好，你修改的方式应该是正确的，现在训练起来具体还有什么问题呢

**Comment by huanmofazong** [comment]
> @huanmofazong 你好，你修改的方式应该是正确的，现在训练起来具体还有什么问题呢

暂时运行的部分可以了，先谢谢您

**Comment by huanmofazong** [comment]
> @huanmofazong 你好，你修改的方式应该是正确的，现在训练起来具体还有什么问题呢

您好，不好意思再次来打扰您，请问一下这个fc=False的时候的具体是什么作用，看了代码不是特别明白

**Comment by huanmofazong** [comment]
@zwx8981 您好，不好意思再次来打扰您，请问一下这个fc=False的时候的具体是什么作用，看了代码不是特别明白

**Comment by zwx8981** [comment]
@huanmofazong fc=True时只训练最后一个全连接层，fc=False时训练全部网络

**Comment by huanmofazong** [comment]
您好，非常不好意思又来问一下，我发现在fc= False的时候，为什么代码当中，con1和bn1的权重还是被关闭了。

            for param in self.basemodel1.conv1.parameters():
                param.requires_grad = False
            for param in self.basemodel1.bn1.parameters():
                param.requires_grad = False

            for param in self.basemodel2.conv1.parameters():
                param.requires_grad = False
            for param in self.basemodel2.bn1.parameters():
                param.requires_grad = False

**Comment by zwx8981** [comment]
@huanmofazong 这里主要是为了提速，conv1对最后的性能几乎没有影响，所以也freeze了

**Comment by huanmofazong** [comment]
> @huanmofazong 这里主要是为了提速，conv1对最后的性能几乎没有影响，所以也freeze了

好的，太感谢您的及时回复。
